#coding=utf-8
import cPickle as pickle

dic_transform = {
    "aix":"ajax",
    "ajax3":"ajax",
    "algorithms":"algorithm",
    "amazone":"amazon",
    "analyse":"analyses",
    "analysers":"analyses",
    "analysing":"analyses",
    "analysisfamiliar":"analyses",
    "analystabout":"analyses",
    "analystfocus":"analyses",
    "analysts":"analyses",
    "analytic":"analyses",
    "analytical":"analyses",
    "analytically":"analyses",
    "analytics":"analyses",
    "analyzed":"analyses",
    "analyzer":"analyses",
    "analyzers":"analyses",
    "analyzes":"analyses",
    "andorid":"android",
    "andriod":"android",
    "androidapp":"android",
    "androidhttp":"android",
    "androidios":"android",
    "androind":"android",
    "anorid":"android",
    "angular":"angularjs",
    "apps":"app",
    "architectural":"architects",
    "architectures":"architects",
    "assembiy":"assmebly",
    "assembled":"assmebly",
    "assembler":"assmebly",
    "assembling":"assmebly",
    "assemblybios":"assmebly",
    "autocad1":"autocad",
    "autodesk":"autocad",
    "automate":"automation",
    "automated":"automation",
    "automating":"automation",
    "automotive":"automation",
    "bachelors":"bachelor",
    "backbone":"backbonejs",
    "backed":"backend",
    "bashshel":"bash",
    "bootstrapangularjsmvc":"bootstrap",
    "bootstrapexperience":"bootstrap",
    "browserfamiliar":"browser",
    "browserify":"browser",
    "browsers":"browser",
    "browserstrong":"browser",
    "c+":"c++",
    "classified":"classification",
    "cleanliness":"cleaning",
    "cleansing":"cleaning",
    "clusters":"clustering",
    "cluster":"clustering",
    "coffeescriptexperience":"coffeescript",
    "compile":"compiler",
    "compiled":"compiler",
    "compilers":"compiler",
    "compiling":"compiler",
    "completed":"compiler",
    "completes":"compiler",
    "completing":"compiler",
    "completion":"compiler",
    "compliant":"compiler",
    "complies":"compiler",
    "compress":"compression",
    "consoles":"console",
    "consultancy":"consulting",
    "consultants":"consulting",
    "consultation":"consulting",
    "consultative":"consulting",
    "controllers":"controller",
    "css1":"css",
    "css3":"css",
    "debug":"debugging",
    "debuggingthe":"debugging",
    "debugs":"debugging",
    "decode":"decoding",
    "decoder":"decoding",
    "devops":"devop",
    "diagramming":"diagram",
    "diagrams":"diagram",
    "documentations":"documentation",
    "documentationsrequirements":"documentation",
    "documented":"documentation",
    "documenting":"documentation",
    "documents":"documentation",
    "dreamwaver":"dreamweaver",
    "dreamweave":"dreamweaver",
    "embed":"embedded",
    "embeded":"embedded",
    "ethercat":"ethernet",
    "firewall12":"firewall",
    "firewallcacti":"firewall",
    "firewalll":"firewall",
    "firewalls":"firewall",
    "firwall":"firewall",
    "frameworks":"framwork",
    "fw":"firmware",
    "github":"git",
    "githubexperience":"git",
    "gp":"gpgpu",
    "graph":"gpgpu",
    "graphic":"gpgpu",
    "graphics":"gpgpu",
    "hibernatejpa":"hibernate",
    "hibernet":"hibernate",
    "hiveql":"hive",
    "hypervisors":"hypervisor",
    "javascrip":"javascript",
    "javascript4":"javascript",
    "javascriptasp":"javascript",
    "javascriptself":"javascript",
    "javasscript":"javascript",
    "js":"javascript",
    "java1":"java",
    "java2":"java",
    "javabean":"java",
    "javac":"java",
    "jekins":"jenkins",
    "knockout":"knockoutjs",
    "labviewc":"labview",
    "laravl":"laravel",
    "linuxc":"linux",
    "linuxlanguage":"linux",
    "liunx":"linux",
    "mango":"mongodb",
    "mangodb":"mongodb",
    "mcba":"mcdba",
    "mpeg1":"mpeg",
    "mssqlserver":"mssql",
    "multithreading":"multithread",
    "mvc2":"mvc",
    "mysql1":"mysql",
    "mysqlerp":"mysql",
    "mysqlhtml":"mysql",
    "mysqlmssqlfirebird":"mysql",
    "mysqlplus":"mysql",
    "mysqlsql":"mysql",
    "node":"nodejs",
    "obj":"objective-c",
    "objective c":"objective-c",
    "optimizationcomputation":"optimization",
    "optimizations":"optimization",
    "orace":"oracle",
    "oracel":"oracle",
    "oracle1":"oracle",
    "oracle11goracle12c":"oracle",
    "oraclecim":"oracle",
    "oracleerp":"oracle",
    "oraclejde":"oracle",
    "oracleos":"oracle",
    "orcale":"oracle",
    "orcle":"oracle",
    "pb":"pbd",
    "pbd1":"pbd",
    "pbd2":"pbd",
    "pbd3":"pbd",
    "pbd4":"pbd",
    "php5":"php",
    "php7":"php",
    "phpcms":"php",
    "phphtml":"php",
    "phpmyadmin":"php",
    "phpmysql":"php",
    "phpmysqllinux":"php",
    "phpphp":"php",
    "phpwind":"php",
    "pythonc":"python",
    "pythonexpert":"python",
    "pythonlinux":"python",
    "qatester":"qa",
    "ps":"photoshop",
    "router":"router",
    "routers":"router",
    "routines":"router",
    "routing":"router",
    "scdma":"schemadesign",
    "schedma":"schemadesign",
    "schema":"schemadesign",
    "schemas":"schemadesign",
    "schematic":"schemadesign",
    "schematics":"schemadesign",
    "servlet":"",
    "servlets":"servlet",
    "socketio":"socket",
    "sockets":"socket",
    "struts1":"struts",
    "struts2":"struts",
    "struts2hibernate":"struts",
    "struts2hibernatezend":"struts",
    "strutshibernate":"struts",
    "strutus":"struts",
    "tomcatadvantage":"tomcat",
    "tomcatnginxbindnfs":"tomcat",
    "tomcatweblogic":"tomcat",
    "unixl":"unix",
    "visualisation":"visualization",
    "vmare":"vmware",
    "vmware1":"vmware",
    "workstations":"workstation",
    "vb":"visual basic",
      }

#轉換字典組合
# dic_gartner = pickle.load(file('dic\dic_gartner.data'))
# dic_techno = pickle.load(file('dic\dic_techno.data'))
# dic_whatis = pickle.load(file('dic\dic_whatis.data'))
#
# dic_transform.update(dic_techno)
# dic_transform.update(dic_whatis)
# dic_transform.update(dic_gartner)

f = file('dic\dic_transform_ori.data', 'w')
pickle.dump(dic_transform,f)

#專業set組合
set_gartner = pickle.load(file('dic\set_gartner.data'))
set_techno = pickle.load(file('dic\set_techno.data'))
set_whatis = pickle.load(file('dic\set_whatis.data'))
set_ori = pickle.load(file('dic\ori_set.data'))

set_pro = set_gartner | set_techno | set_whatis | set_ori
#
# print len(set_pro)
#
#set組合經dic_all轉換 (17000->13000)
# for word in set_pro.copy():
#     if word in dic_transform:
#         set_pro.add(dic_transform[word])
#         set_pro.remove(word)

set_pro.add('sqoop')
set_pro.add('hive')
set_pro.remove('apache sqoop')
set_pro.remove('apache hive')

f = file('dic\set_skill_v1.data', 'w')
pickle.dump(set_pro,f)
#
# skillList = sorted(set_pro,key=len)
#
# print len(skillList)
#
# w = open('dic\skillList.txt','w')
# for each in skillList:
#     w.write(str(each) + '\n')

